### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by rlyalyther** [INFO523-S24/project-final-DaakuDataSingh#1]
The following is the peer review of the project proposal by [data detectives]. The team members that participated in this review are 

- [Ayesha Khatun] - @ayeshakhatunsujana
- [Valerie Okine] - @valerie-okine
- [Alyssa Nether] - @rlyalyther
- [Shreemithra Naveen] - @Shreemithran
- [Toluwanimi Olorunnisola] - @ToluGb
- [Abhishek Kumar] - @Abhi291712

Describe the goal of the project.
- **Prediction of ODI outcomes.** 

Describe the data used or collected.
- **This project is good as it has about 20 years on historical cricket match data. The dataset is very large with great specifics on venues, players, and dates. There appears to be a large amount of data missing and we are curious to know how they will handle this issue.**

Describe how the research question will be answered, e.g. what approaches / methods will be used.
- **They will use regression techniques to determine 2023 ODI match stats using historical data. Win probability using line or area charts. Match outcome predictions using machine learning (but which one?). Player performance analyzed.** 

Is there anything that is unclear from the proposal?
- **A large amount is unclear. (see next question)**

Provide constructive feedback on how the team might be able to improve their project.
1. **The image is cool in the analysis plan but it hard to interpret and make sense of what you all are going to do. Definitive dates would provide a better plan/skeleton for your timeline.** 
2. **Also for the analysis plan, the machine learning techniques are not clear as well**

 What aspect of this project are you most interested in and would like to see highlighted in the presentation.
- **We love the image and the smart creation of it. We are also excited to see how the regression techniques will help to predict these outcomes.** 

Provide constructive feedback on any issues with file and/or code organization.
1.  **clean up the second cell block in the dataset area** 
2. **the cell library block can be hidden** 
3. **It would be helpful if you all mention a glimpse of the data such as data types, dataset dimensions, and important columns used in analysis.** 
4. **add a timeline**
5. **create more structure to your idea.. you have potential, it just has to be harnessed!**

Any further comments or feedback?
- **create an introduction part that includes a slight information about what cricket is so everyone can know what is being discusses**
- **why is there a title for the class in both photos? We recommend that being removed.** 
![daaku](https://github.com/INFO523-S24/project-final-DaakuDataSingh/assets/156706571/64e0cedd-f06f-4908-83c2-2e810c80bb02)

**anyways, all the best!! you got this Daako Data Singh :D**

**Comment by christian-ortmann** [comment]
Thank you for your feedback! We plan be more descriptive with the data presentation and have taken your other comments into consideration as well.
