### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by navyaa-reddy** [INFO523-S24/project-final-DaakuDataSingh#2]
The following is the peer review of the project proposal by Mining Minds. The team members that participated in this review are 

- Roxana Akbarsharifi- @rxnsh

- Omid Zandi - @zandi-omid

- Deema Albluwi - @Dee-koudz

- Gowtham Gopalakrishnan - @Gowtham-18

- Nandhini Anne - @NandhiniAnne

- Sai Navya Reddy Busireddy - @navyareddy152

- Describe the goal of the project.
The main goal of the project is to predict ODI outcomes, and player performances through an interactive dashboard.

- Describe the data used or collected.
The dataset consists of two csv files which combined would give the ODI cricket match statistics of the last 20 years.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Two research goals have been mentioned. 

Match Outcome Prediction:
Use historical match data and machine learning algorithms to predict the outcome of ongoing matches based on current match conditions (e.g., runs scored, wickets fallen, overs bowled).
Display the predicted winner and the probability of each team winning the match.

Player Performance Prediction:
Predict the performance of individual players during the match, including runs scored, wickets taken, and player of the match contenders.
Utilize player statistics, recent form, and match conditions to generate these predictions.

- Is there anything that is unclear from the proposal?

A few things are unclear. The approach to their research goals is vague, they are going in many directions. And the outcomes of their project are complicated to understand.

- Provide constructive feedback on how the team might be able to improve their project.
The team could have been more specific on what variables of data they are going to use for each of their research goals. Also more specific on what they are planning to display at the end, is it match outcome (win/lose), batting/bowling trends of player or win probability trends.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
The idea of mocking live cricket match statistics and providing a real-time experience of a cricket match is very exciting.

- Provide constructive feedback on any issues with file and/or code organization.
The data files are not appropriate in the files. Organize the data correctly and upload them.

- (Optional) Any further comments or feedback?

**Comment by christian-ortmann** [comment]
Thank you for your feedback! We plan to narrow down our approach and have taken your other comments into consideration.
