### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by shreemithran** [INFO523-S24/project-final-DaakuDataSingh#4]
The following is the peer review of the project code by Data Detectives. The team members that participated in this review are 

[Ayesha Khatun] - @ayeshakhatunsujana
[Valerie Okine] - @valerie-okine
[Alyssa Nether] - @rlyalyther
[Shreemithra Naveen] - @shreemithran
[Toluwanimi Olorunnisola] - @ToluGb
[Abhishek Kumar] - @Abhi291712

#### 1. Purpose of Code
- [ ] Clearly defined and understood
- [x] Ambiguous or unclear

--- 

#### 2. Code Quality

- [x] Code is clean, readable, and well-organized
- [x] Adequate comments explaining complex or tricky code sections
- [x] Variables, methods, and classes have meaningful names
- [x] Consistent code style (indentation, naming conventions, etc.)

---

#### 3. Functionality

- [x] Code functions as intended and produces the expected outcome
- [ ] Edge cases have been considered and handled
- [x] No obvious bugs or issues found

---

#### 4. Testing

- [x] Adequate unit tests covering key functionality
- [x] Tests are clear and can be easily understood
- [x] All tests pass successfully

---

#### 5. Documentation

- [ ] Code documentation (e.g., docstrings, comments) is sufficient
- [x] Readme or other documentation updated if necessary

---

#### 6. Best Practices

- [x] No hardcoded values; constants used appropriately
- [x] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [x] Code avoids repetition and promotes reusability

---

#### 7. Additional Comments

- In "Index.qmd", Adding a new line after common makes it readable.- (Line No: 119)
- Spacing between equal to symbol ( = ) - Line no 129
- Better comments for a better understanding of the code for viewers.
- Commit comments are not unique and don't signify the actual changes
- Repo organization is not included in the "Index.qmd" file
- Distribution of work is not mentioned in any of the "qmd" files.
---

#### 8. Recommendation

- [ ] Approved - ready to be merged
- [x] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by tezz-us** [comment]
Thankyou for your feedback !!
