### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by rlyalyther** [INFO523-S24/project-final-DaakuDataSingh#6]
The following is the peer review of the Presentation proposal by [data detection]. The team members that participated in this review are 

[Ayesha Khatun] - [[@ayeshakhatunsujana](https://github.com/ayeshakhatunsujana)]
[Valerie Okine] - [[@valerie-okine](https://github.com/valerie-okine)]
[Alyssa Nether] - [[@rlyalyther](https://github.com/rlyalyther)]
[Shreemithra Naveen] - [[@shreemithran](https://github.com/shreemithran)]
[Toluwanimi Olorunnisola] - [[@ToluGb](https://github.com/ToluGb)]
[Abhishek Kumar] - [[@Abhi291712](https://github.com/Abhi291712)]

- Content: Is the research question well designed and is the data being used relevant to the research question?

Yes, the question was well thought out and the data shows results relating to the questions. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

Yes, they provided some great visualizations but could have benefitted from having one or two graphing showing description analysis. 

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

More colors and pictures could have been incorporated to capture the viewer's attention. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

All slides were well organized. All plots have proper labels and titles. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

They spoke clearly and each member got an equal opportunity to speak. They had smooth transitions between people and did not read off the script.

**Comment by christian-ortmann** [comment]
Thank you for your feedback!
